name = "C3D"
uuid = "de436766-0b2a-5f82-bc5b-1ccc5f599b83"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.6.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
VaxData = "a6f58a78-e649-57e2-81bc-1d865c7b74f7"

[compat]
julia = "1"
VaxData = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
