name = "C3D"
uuid = "de436766-0b2a-5f82-bc5b-1ccc5f599b83"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.7.3-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
VaxData = "a6f58a78-e649-57e2-81bc-1d865c7b74f7"

[compat]
VaxData = "0.5,0.6,1"
SnoopPrecompile = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
